SELECT product_dim.product_title as product_title,   
product_dim.product_id as product_id,          	                                 	                    
product_dim.brand as brand,           	                    
product_dim.color as color,            	                        	                               	                    
product_dim.weight as weight,            	                    
product_dim.length as length,             	                    
product_dim.breadth as breadth,            	                    
product_dim.height as height, 
product_dim.type as type,            	                    
product_dim.variant as variant,           	                                  	                            	                    
product_dim.design as design,             	                    
product_dim.pattern as pattern,            	                    
product_dim.occasion as occasion,             	                    
product_dim.outer_material as outer_material,             	                    
product_dim.material as material,            	                    
product_dim.sleeve as sleeve,             	                                 	                               	                              	                    
product_dim.euro_size as euro_size,           	                    
product_dim.uk_india_size as uk_india_size,             	                    
product_dim.us_size as us_size,          	                                 	                                 	                    
product_dim.designed_for as designed_for,            	                                	                    
product_dim.size_in_number as size_in_number,             	                    
product_dim.size as size,            	                             	                                 	                    
product_dim.new_display_size as new_display_size,             	                                  	                                	                    
product_dim.size_chart as size_chart, 
rvp_fact.order_item_id AS order_item_id,
rvp_fact.account_id AS account_id,
rvp_fact.return_item_reason AS return_reason,
rvp_fact.return_item_sub_reason AS return_sub_reason,
rvp_fact.return_comments AS return_comments,
rvp_fact.return_item_request_date_time AS return_item_date
FROM bigfoot_external_neo.sp_product__product_attribute_hive_dim product_dim
INNER JOIN bigfoot_external_neo.scp_rrr__return_l2_id_level_hive_ss_fact rvp_fact ON rvp_fact.returned_product_id_key = product_dim.product_attribute_hive_dim_key
WHERE product_dim.analytic_vertical IN ('MensPoloTShirt')
AND rvp_fact.return_item_sub_reason IN ( 'FIT_DO_NOT_LIKE' , 'SIZE_LARGER' , 'SIZE_SMALLER' , 'SIZE_WAS_SMALLER' , 'FIT_NOT_AS_EXPECTED' , 'SIZE_WAS_LARGER');